Fetch even when no args provided

diff --git a/fizzbuzz b/fizzbuzz
--- a/fizzbuzz
+++ b/fizzbuzz
@@ -14,11 +14,6 @@ Options:
 Examples:
     fizzbuzz 5          Get page 5, 100 results            (from 401 to 500)
     fizzbuzz 3 50       Get page 3, 50 results             (from 151 to 200)
-
-Status codes:
-    0 - successful
-    1 - illegal option
-    2 - failed to fetch
 '
 
 for arg in "$@"; do
@@ -28,17 +23,14 @@ for arg in "$@"; do
       exit;;
 
     -v|--version)
-      echo 1.1.0
+      echo 1.2.0
       exit;;
 
     -*)
       >&2 echo "fizzbuzz: illegal option $arg"
       echo "$help"
-      exit 1;;
-
-    *)
-      curl "$endpoint" || echo "fizzbuzz: Failed to fetch - is the API running on http://localhost:4000/?"
-      exit 2
+      exit 1
   esac
 done
 
+curl "$endpoint" || echo "fizzbuzz: Failed to fetch - is the API running on http://localhost:4000/?"
